#ifndef COMPILER_SRC_MODELS_ANALYZER_SEMANTIC_TYPE_H_
#define COMPILER_SRC_MODELS_ANALYZER_SEMANTIC_TYPE_H_

enum EType {
  UNKNOWN_TYPE,
  SCALAR_TYPE = 401,
  REFERENCE_TYPE = 405,
};

class Type {

};

#endif //COMPILER_SRC_MODELS_ANALYZER_SEMANTIC_TYPE_H_
